# Basic
title: 褚毅博
subtitle: 个人站
welcome_message: 欢迎来到我的个人站~

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: empty

# Pagination
paginate: 10
paginate_path: "page/:num/"


